Metrics/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 115

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20