Metrics/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 160

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 45

Style/ClassAndModuleChildren:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false